### ISSUE TITLE
[Performance] Remove distincts when metering point periods are fixed

### ISSUE THREAD

**Issue by johevemi** [Energinet-DataHub/opengeh-wholesale#1728] opened 2023-12-11 08:36 UTC
Remove distincts in metering_point_time_series.py lin 62 and 87, when metering point period data from the migrations domain has removed duplicates, blocked until then.

**Comment by BjarkeMeier** [comment] 2024-02-28 07:01
@johevemi is this issue still blocked?

**Comment by JesperGomes** [comment] 2024-04-02 09:42
@khatozen will talk to Volt and verify if it is unblocked. Note: maybe we can never remove distinct, if Volt can't prepare it without duplicates

**Comment by khatozen** [comment] 2024-04-02 11:18
@JesperGomes 
I talked to Peter and he confirmed that, we don't need to use distinct in the selection of metering points from the metering_point_periods, as Volt doesn't send us a duplicate line.

From Peter:
Vi kan håndtere målepunktsopdateringer, så bør I ikke se flere duplikater.
Hvis vi får en nyere opdatering ind på en given dato, så tolker vi det som en opdatering - og hvis nogle af felterne er relevant i forhold til hvad vi skriver hos jer, så opdaterer Databricks dem i wholesale

**Comment by khatozen** [comment] 2024-04-19 11:57
This story can be closed as we should keep the distinct in the selection on metering_point_periods.
Peter Tandrup has confirmed that the same metering point period can occurs several times in the table, due to the updates on other master data attributes, that do not affect the calculation.
example from production:
<img width="1600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3A0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8fc6518401c093f64769578a00e5d8d2c0eb3b3/image.png" alt="image.png" />

**Closed by khatozen** 2024-04-19 11:57 UTC
Labels: Team Mandalorian, Tech
