### ISSUE TITLE
[Duplicate] [Performance] Spark configuration tuning

### ISSUE THREAD

**Issue by slb-halfspace** [Energinet-DataHub/opengeh-wholesale#1656] opened 2023-11-20 14:14 UTC

**Comment by cenh-halfspace** [comment] 2023-11-23 08:23
Duplicate of: https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/103

**Closed** 2023-11-23 08:22 UTC
Labels: Team Mandalorian
