### ISSUE TITLE
DoD på story template i Zenhub

### ISSUE THREAD

**Issue by ClausQAEnerginet** [Energinet-DataHub/opengeh-wholesale#1971] opened 2024-03-06 07:36 UTC

**Comment by BjarkeMeier** [comment] 2024-03-19 07:36
@ClausQAEnerginet , duplicate of [this](https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/team-mandalorian/238)?

**Closed** 2024-03-21 08:34 UTC
Labels: Team Mandalorian
